# Generated by Django 5.2.4 on 2025-09-22 11:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='رقم الجوال')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان')),
                ('user_id', models.CharField(max_length=100, unique=True, verbose_name='رقم الهوية')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_index=True, max_length=255, verbose_name='اسم المنشأة')),
                ('company_number', models.CharField(max_length=100, verbose_name='رقم المنشأة')),
                ('region', models.CharField(db_index=True, max_length=100, verbose_name='اسم المنطقة')),
                ('street_name', models.CharField(max_length=255, verbose_name='اسم الشارع')),
                ('building_number', models.CharField(max_length=50, verbose_name='رقم العقار')),
                ('activity_type', models.CharField(max_length=100, verbose_name='نوع النشاط')),
                ('electricity_meter_number', models.CharField(max_length=50, verbose_name='رقم الكهرباء')),
                ('actual_workers_count', models.IntegerField(default=0, verbose_name='عدد العمال الفعلي')),
                ('establishment_type', models.CharField(choices=[('commercial_shop', 'محل تجاري'), ('commercial_building', 'عقار تجاري'), ('factory', 'مصنع'), ('lab', 'معمل'), ('apartment', 'شقة'), ('workshop', 'ورشة'), ('office', 'مكتب'), ('villa', 'فيلا'), ('other', 'اخرى')], max_length=50, verbose_name='المنشأة عبارة عن')),
                ('size_description', models.TextField(verbose_name='حجم المنشأة والمساحة التقريبية بالوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ إضافة الشركة')),
                ('status', models.CharField(default='active', max_length=50, verbose_name='الحالة')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_inspected', to=settings.AUTH_USER_MODEL, verbose_name='المفتش المعين')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_managed', to=settings.AUTH_USER_MODEL, verbose_name='المدير المسؤول')),
            ],
            options={
                'verbose_name': 'منشأة',
                'verbose_name_plural': 'منشآت',
            },
        ),
        migrations.CreateModel(
            name='CompanyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='company_images/', verbose_name='الصورة')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='وصف الصورة')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspectors.company', verbose_name='اسم المنشأة')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ التفتيش')),
                ('workers_size_estimation', models.CharField(max_length=255, verbose_name='تقدير المفتش لحجم العمالة')),
                ('license_compliance', models.CharField(choices=[('compliant', 'مطابقة'), ('non_compliant', 'غير مطابقة'), ('unspecified', 'غير محدد')], max_length=50, verbose_name='مطابقة الرخصة للموقع')),
                ('female_workers_element', models.CharField(choices=[('feasible', 'قابل'), ('not_feasible', 'غير قابل'), ('unspecified', 'غير محدد')], max_length=50, verbose_name='العنصر النسائي')),
                ('unlicensed_workers', models.CharField(choices=[('non_violation', 'غير مخالف'), ('violation', 'مخالف'), ('unspecified', 'غير محدد')], max_length=50, verbose_name='استخدام عمال دون ترخيص')),
                ('penalties_regulation', models.CharField(choices=[('exists', 'يوجد'), ('not_exists', 'لا يوجد'), ('not_applicable', 'لا ينطبق')], max_length=50, verbose_name='لائحة الجزاءات')),
                ('work_regulation', models.CharField(choices=[('exists', 'يوجد'), ('not_exists', 'لا يوجد'), ('not_applicable', 'لا ينطبق')], max_length=50, verbose_name='لائحة تنظيم العمل')),
                ('worker_file_maintenance', models.CharField(choices=[('non_violation', 'غير مخالف'), ('violation', 'مخالف'), ('unspecified', 'غير محدد')], max_length=50, verbose_name='الاحتفاظ بملف خاص لكل عامل')),
                ('extended_working_hours', models.CharField(choices=[('non_violation', 'غير مخالف'), ('violation', 'مخالف'), ('unspecified', 'غير محدد')], max_length=50, verbose_name='تشغيل العامل أكثر من الساعات المحددة')),
                ('consecutive_shifts', models.CharField(choices=[('non_violation', 'غير مخالف'), ('violation', 'مخالف'), ('unspecified', 'غير محدد')], max_length=50, verbose_name='تشغيل العامل أكثر من جمعتين متتاليتين')),
                ('weekly_rest_schedule', models.CharField(choices=[('non_violation', 'غير مخالف'), ('violation', 'مخالف'), ('unspecified', 'غير محدد')], max_length=50, verbose_name='جدول ساعات العمل والراحة الأسبوعية')),
                ('number_of_shifts', models.CharField(choices=[('one_shift', 'وردية واحدة'), ('two_shifts', 'ورديتان'), ('three_shifts', 'ثلاثة ورديات')], max_length=50, verbose_name='عدد ورديات العمل')),
                ('inspector_opinion', models.TextField(verbose_name='رأي المفتش')),
                ('mandoub_name_1', models.CharField(blank=True, max_length=100, verbose_name='اسم المندوب (1)')),
                ('mandoub_phone_1', models.CharField(blank=True, max_length=20, verbose_name='رقم الجوال (1)')),
                ('mandoub_name_2', models.CharField(blank=True, max_length=100, verbose_name='اسم المندوب (2)')),
                ('mandoub_phone_2', models.CharField(blank=True, max_length=20, verbose_name='رقم الجوال (2)')),
                ('status', models.CharField(default='draft', max_length=50, verbose_name='الحالة')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspectors.company', verbose_name='اسم المنشأة')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المفتش')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inspection_images/', verbose_name='الصورة')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='وصف الصورة')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspectors.inspection', verbose_name='تقرير التفتيش')),
            ],
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['company_name', 'region'], name='inspectors__company_94457d_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['inspector', 'inspection_date'], name='inspectors__inspect_866a22_idx'),
        ),
    ]
