# Generated by Django 5.2.4 on 2025-09-28 10:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status_by_inspector',
            field=models.CharField(choices=[('not_assigned', 'لم يتم التعيين'), ('assigned', 'تم التعيين'), ('accepted', 'تم القبول'), ('declined', 'تم الرفض'), ('in_progress', 'قيد العمل'), ('completed', 'مكتملة')], default='not_assigned', max_length=20, verbose_name='حالة التعيين'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='العنوان'),
            preserve_default=False,
        ),
    ]
