# Generated by Django 5.2.4 on 2025-09-28 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0002_company_status_by_inspector_alter_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='decline_reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب الرفض'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
                ('related_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspectors.company', verbose_name='الشركة المتعلقة')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'إشعارات',
                'ordering': ['-created_at'],
            },
        ),
    ]
