# Generated by Django 5.2.4 on 2025-10-12 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0003_company_decline_reason_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_inspectors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('pending_approval', 'بانتظار الموافقة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('archived', 'مؤرشف'), ('deleted', 'محذوف')], default='draft', max_length=50, verbose_name='الحالة'),
        ),
    ]
