# Generated by Django 5.2.4 on 2025-11-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0005_alter_inspection_inspector'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
    ]
