# Generated by Django 5.2.4 on 2025-11-19 18:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0006_inspection_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
    ]
