# Generated by Django 5.2.4 on 2025-11-19 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0007_inspection_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='created_at',
        ),
    ]
