# Generated by Django 5.2.4 on 2025-11-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0008_remove_inspection_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الانضمام'),
        ),
    ]
