# Generated by Django 5.2.4 on 2026-10-06 17:44

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspectors', '0009_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyimage',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='company_images/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='inspectionimage',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='inspection_images/', verbose_name='الصورة'),
        ),
    ]
